version: '3.8'
services:

  loadbalancer:
    build: haproxy/.
    ports:
      - 1080:80
    deploy:
      mode: gloabl

  worker:
    expose:
      - "8080"
    build: tomcat/.
    deploy:
      replicas: 2
    depends_on:
      - memcache
      - memcache_manager

  memcache: &memcache
    image: memcached

  memcache_manager: 
    <<: *memcache
    deploy:
      placement:
        constraints:
          - node.role == manager
